### ISSUE TITLE
No jump sound effect in Pitfall!

### ISSUE THREAD

**Issue by dukesilverfan** [MiSTer-devel/Atari2600_MiSTer#1]
I noticed there is no jumping sound effect while playing Pitfall!, but other sound effects, such as taking damage from a rolling log do play just fine.

This was noticed on the newest Atari2600_20180308.rbf release, with no SDRAM module installed.

**Comment by dukesilverfan** [comment]
Just as an update, Pitfall! is still missing the jumping sound with the newest 20181214 release. Adding the SDRAM module did not change anything.

**Comment by dgoswick** [comment]
I am also experiencing the same issue in release 20181214.

**Comment by dukesilverfan** [comment]
Every release I try again, and Atari2600_20190308.rbf still has no jump sound effect in Pitfall. I was reading that mappers can be forced via the extension. Would it be possible to correct this glitch by forcing a different mapper?

**Comment by dgoswick** [comment]
I don't think a different mapper would make any difference.  Apparently this is a known issue.
http://www.atari-forum.com/viewtopic.php?t=33358
I try this after every update of the Atari2600 core, and this issue persists.
Hopefully someone can figure this out one day, as Pitfall is one of my favorite games.  Luckily I can still play it on original hardware.

**Comment by gwaland** [comment]
Looks like this was fixed in today's release.

**Comment by dgoswick** [comment]
The audio seems to be working in Pitfall! now.  Thank you!

**Comment by dukesilverfan** [comment]
Verified working. Thank you devs!
