### ISSUE TITLE
Haunted House starts with player stuck in the wall

### ISSUE THREAD

**Issue by dannyowelch** [MiSTer-devel/Atari2600_MiSTer#11]
Tested with rom that works in Retroarch and Stella.  The player starts on the left of the screen rather than the usual position on the right and is stuck in the wall.

**Comment by rarcos** [comment]
Apparently this got fixed on MiST. Is it possible to port the fix to MiSTer?

**Comment by sorgelig** [comment]
Do you know where is the A2600 repo for MiST?

**Comment by rarcos** [comment]
This seems to be the repo: https://github.com/wsoltys/tca2601

According to MiST changelog, the fix was implemented mid January.

**Comment by sorgelig** [comment]
according to history, this fix was already applied some time ago but later got removed with unknown reason.

**Comment by SegaSnatcher** [comment]
I'm not having this issue on latest release.

**Comment by rarcos** [comment]
Tested latest release and the game works. Could finish it.
