### ISSUE TITLE
In Checkers, the screen doesn't go black while the computer is thinking

### ISSUE THREAD

**Issue by OskarSigvardsson** [MiSTer-devel/Atari2600_MiSTer#14]
Checkers for the 2600 had the notoriously terrible feature that whenever the computer was thinking, the entire screen went black. [Here is a video demonstrating it.](https://youtu.be/XUT3LShJEyQ)

On the MiSTer however, the screen just freezes while the computer is thinking, it doesn't go black. Although it is arguably an improvement on the original, it isn't exactly accurate 🙂

**Comment by NML32** [comment]
@OskarSigvardsson checkers screen now blanks out now when the computer is thinking with Atari2600_20200908.rbf

**Comment by PhantombrainM** [comment]
Latest public release fixes issue: https://github.com/MiSTer-devel/Atari2600_MiSTer/commit/c65b62c251d877a9c0c2cbc599adb24abee50661

Ticket can be closed.
