### ISSUE TITLE
Pitfall II Corrupted Graphics

### ISSUE THREAD

**Issue by NML32** [MiSTer-devel/Atari2600_MiSTer#16]
With the latest commit (012e85c dated 20200818), Pitfall II displays corrupted graphics. 
The last commit a78e596 20200516 worked fine and so did the previous release Atari2600_20200511.rbf

Using file extension .p2 (Pitfall II - Lost Caverns (USA).p2)

**Comment by dtungsten** [comment]
Pitfall II graphics were corrupted in the previous release Atari2600_20200511.rbf. I don't know about commit https://github.com/MiSTer-devel/Atari2600_MiSTer/commit/a78e596575fbc04665dd66857348cec00f0d44aa though.

**Comment by NML32** [comment]
@dtungsten Try changing Pitfall II extension to .p2
No corruption in Atari2600_20200511.rbf if you load Pitfall2.p2

**Comment by dtungsten** [comment]
It does have the extension p2.  It wouldn't even load with the extension a26.

**Comment by dtungsten** [comment]
Oh, I just loaded it in the new version and the graphics are completely corruped. There are graphical glitches in Atari2600_20200511.rbf, though.

**Comment by NML32** [comment]
![20200820_102630-Pitfall II - Lost Caverns (USA)](https://user-images.githubusercontent.com/6879399/90785072-f1240a00-e2cf-11ea-9390-4934712da605.png)
Sorry, I should have attached a pic. This screenshot was taken via MiSTer screen capture.

**Comment by dtungsten** [comment]
@NML32 No, that's entirely my fault for not fully researching the new build before saying something. Also for conflating glitches with corruption.

**Comment by NML32** [comment]
I'm closing this issue. Fixed as of Atari2600_20200824.rbf
