### ISSUE TITLE
Bobby is Going Home: corrupted graphics

### ISSUE THREAD

**Issue by skooterblog** [MiSTer-devel/Atari2600_MiSTer#18]
The latest release of the core has some corrupted graphics in Bob is Going Home (USA), specifically in the last screen of the stage, with the house. This video shows this behavior:

https://youtu.be/p2L4-on7a7E?t=456

**Comment by NML32** [comment]
Screen corruption fixed as of Atari2600_20200824.rbf

**Comment by skooterblog** [comment]
I can confirm the corruption is fixed in this new version. Thank you.
