### ISSUE TITLE
SNAC support?

### ISSUE THREAD

**Issue by thorr2** [MiSTer-devel/Atari2600_MiSTer#20]
Hello, can you please merge the SNAC code into the main core?  I have an unofficial core that is getting old that supports paddle games via SNAC and I would love to be able to get the new updates and use my paddles.  Thanks!

**Comment by edburns** [comment]
Hello @thorr2 I looked at your repositories and do not see a fork for this "unofficial core"?  Can you please share how we can get a look at it?

**Comment by sorgelig** [comment]
This core is superseded by Atari 7800 core. Any further updates should go to Atari 7800 repository.
