### ISSUE TITLE
OSD doesn't display on analog output

### ISSUE THREAD

**Issue by redsteakraw** [MiSTer-devel/Atari2600_MiSTer#21]
I can launch a game and the OSD displays but when I go to switch to a new game the OSD won't display.  It does display over HDMI but is absent when using the analog output with the IO board.  I am using component output and have a V6 IO board.

**Comment by redsteakraw** [comment]
Did some more testing it seems to only happen when you launch certain games.  Custer's Revenge being one of them.

**Comment by NML32** [comment]
@redsteakraw Try the version @paulb-nl posted on the MiSTer Forum. I tried it and it seems to fix the issue you reported.  That version seems to fix issues with a lot of A2600 ROMs.  
https://misterfpga.org/viewtopic.php?p=9875#p9875

Hopefully, whatever fixes he made to the A2600 core gets added to the official MiSTer core.

**Comment by PhantombrainM** [comment]
Problem is solved in latest public release https://github.com/MiSTer-devel/Atari2600_MiSTer/commit/c65b62c251d877a9c0c2cbc599adb24abee50661

Ticket can be closed.
