### ISSUE TITLE
Feature Request: Pause Button

### ISSUE THREAD

**Issue by skooterblog** [MiSTer-devel/Atari2600_MiSTer#23]
This is not a bug, but rather a feature request: the Atari 2600 core could use a pause button. 

Some games, like "Enduro", can result in really long sessions. It was ok when I was a kid with not many real obligations, but now everything happens while I'm playing: phone rings, wife calls, etc.

I have the real hardware in which I included a pause button (2600RGB mod), but I prefer to play on MiSTer for convenience.

**Comment by sorgelig** [comment]
it's not a problem to make pause button but it will turn off CRT video.
Video in Atari 2600 is rendered with CPU help. If CPU is stopped then no VSync will be generated.
HDMI is less affected as it simply will show last rendered frame..

**Comment by skooterblog** [comment]
That's totally acceptable. The mods for the real hardware also turns off the video or shows random patterns.

**Comment by skooterblog** [comment]
Thank you very much for implementing this feature. I just tested it in dozens of games and it worked in all of them.
