### ISSUE TITLE
Air-Raid (Men-A-Vision) PAL doesn't sync

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/Atari2600_MiSTer#25]
This game doesn't sync on CRT (screen / picture runs through). HDMI not tested.

Edit: Same issue on "Schnapp die Apfeldiebe (PAL) aka Catch Time (1983)".

**Comment by paulb-nl** [comment]
They work fine on my CRT. These games use strange timings (~290 lines @ 54Hz). Maybe your CRT does not like that.

**Comment by NML32** [comment]
I was able to reproduce the issue on my computer gaming monitor via HDMI. 
No issues on my TV via HDMI, Sony PVM 15 KHz, or CRT TV via the component connection.

**Comment by PhantombrainM** [comment]
Interesting. I've got two CRT's on hand.
I can't get a stable picture on both. It's direct VGA pure singal into scart. 
No direct video VGA HDMI converters.

Consumer Sony 29" KV CRT: https://youtu.be/NkXRfwrSqfI

Sony 14" PVM: https://youtu.be/ZIh2m7jzAWM

**Comment by NML32** [comment]
That looks like the same PVM I'm using. SONY PVM20M2MDU
VGA to BNC. I'm using 4 BNC connectors hooked up like in the picture. 
![Sony PVM BNC Connection](https://user-images.githubusercontent.com/6879399/92997426-3dcebf80-f4e1-11ea-9554-34b2f35a3507.jpg)

**Comment by sorgelig** [comment]
Atari 2600 has non-fixed refresh rate. It fully depends on game.
And this is one of games using out of spec refresh rate.
Nothing to do with core.
