### ISSUE TITLE
Feature Request: Two button support

### ISSUE THREAD

**Issue by NML32** [MiSTer-devel/Atari2600_MiSTer#26]
Feature request.
I was hoping that two-button Joystick support could be added to the A2600 MiSTer core?
I found an article on the AtariAge forum for adding a second fire button to the Atari Joystick or you could use a Sega Genesis/Megadrive controller. 

AtariAge forum topic (includes 2button games and a Genesis test ROM):
https://atariage.com/forums/topic/158430-rom-hacks-to-support-2-buttons-with-genesis-controllers/

[Atari 2 button controller.zip](https://github.com/MiSTer-devel/Atari2600_MiSTer/files/5251642/Atari.2.button.controller.zip)

Thank you

**Comment by Kitrinx** [comment]
It looks like this is simply using one of the paddle signals as a button, that's it. I think you can already achieve compatibility just by mapping your controller.

**Comment by NML32** [comment]
@Kitrinx Unless I'm doing something wrong I can't get it to work. When I press the mpapped paddle button it doesn't work and messes up the other mapped buttons until you press the A button.

**Comment by sorgelig** [comment]
I've tried to implement, but i don't see reaction on it.
Something is missing in description.

**Comment by NML32** [comment]
That's too bad the info in the PDF seemed very promising.

**Comment by sorgelig** [comment]
i've made it

**Comment by NML32** [comment]
Very nice!! 
Thank you. :)

**Comment by NML32** [comment]
The second button works great. :)
Closing ticket.
