### ISSUE TITLE
Compilation in linux fails

### ISSUE THREAD

**Issue by Miguel-T80c** [MiSTer-devel/Atari2600_MiSTer#28]
There is a file rtl/t65/t65.qip that is referenced by the string **rtl/T65/T65.qip** in files.qip.

The compilation works on Windows because its file system is case insensitive but fails in Linux.

The correct line in files.qip is this: set_global_assignment -name QIP_FILE **rtl/t65/T65.qip**

Please, fix this to allow compile in Linux.

**Comment by sorgelig** [comment]
fixed

**Comment by MiSTer-DB9** [comment]
thanx
