### ISSUE TITLE
Feature Request: Mapping Difficulty Switches and B&W Switch to Buttons

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Atari2600_MiSTer#30]
I posted this on the Atari 2600 thread on the MiSTer forum, so this is just a copy and paste of this thread: https://misterfpga.org/viewtopic.php?f=24&p=11338&sid=f2007b5a2b6dc9877b591953fc8bdc7f#p11338

"I have a feature request. Some Atari 2600 games use both the Black and White switch as well as the difficulty switches as additional buttons. This excellent articles goes into detail on the functionality of the B&W switch: http://nerdlypleasures.blogspot.com/201 ... 00s-b.html

TLDR: The B&W Switch has special functionality for these select games:
-Space Shuttle (engine controls)
-Cosmic Ark (turn on/off star field on some cartridges)
-Fantastic Voyage (pause)
-Solaris (inverts planet horizons)
-Mouse Trap (removes playfield)
-Starmaster (brings up Galactic Chart)
-Beany Bopper (pause)
-Flash Gordon (pause)
-Spacemaster X-7 (pause)
-Secret Quest (brings up Status Screen and password)

Obviously the use of a pause button is redundant, but some games like Secret Quest, Space Shuutle and Starmaster are essential to the playability of the game.

Also, the Difficulty switches don't only affect the difficulty of the game, but they also change certain settings according to this thread:https://atariage.com/forums/topic/18858 ... gs-a-or-b/

Moon Patrol, Pengo and Phoenix's music is turned on or off with the Difficulty switches. I know there are other examples of the Difficulty switches acting more as buttons for certain games than switches.

I bring this up because Stella allows you to map the B&W and Difficulty switches to buttons. I prefer to map these switches to all four shoulder buttons. It just makes things easier. Is it realistic to add the B&W and Difficulty switches as buttons as well as a switch within the core menu? I was impressed with how quickly pausing was added to the core, but I just wanted to know what the feasability of this feature is please. It could either possibly be implemented by having difficulty A being one button and difficulty B being another button or you could make the switches one button that pressed once is difficulty A and pressed again is difficulty B. I don't want to make this post too long, but is this feature likely to happen?"

**Comment by skooterblog** [comment]
I second this request as it is essential for the playability of some games and it is just convenient for some others.

**Comment by sorgelig** [comment]
Technically it's not hard to put them to gamepad but it will be hard to use as originally they were tumblers. If emulate press as down position and release as up position then it won't work well in games where tumbler is used as a switch between modes. If emulate press as a switch between up/down on every press then games using tumbler as a short action won't work well because you have to press the button 2 times to simulate short switch up-down-up...

**Comment by skooterblog** [comment]
I think the second option is ok. Are there any games that use the switches as short action? Even if there are, one would have to move the switch twice in the real hardware as well.

**Comment by sorgelig** [comment]
I never had a real 2600. Don't know which mode is used for these tumblers.

**Comment by skooterblog** [comment]
As far as I know, B&W and difficult switches are only used in the first scenario you described. All official Atari 2600 (and probably most clones) use two position switches for the B&W and the difficult switches (B&W being the same switch they use for POWER in most models)

Though these switches all look the same in a six switch Atari, SELECT and START are different from the others. They don't lock in the pressed position and have springs to return to the unpressed position.

**Comment by sorgelig** [comment]
how B/W,P1 difficulty, P2 difficulty should be mapped to joystick 1 and 2?
All 3 switches to both joysticks?

**Comment by skooterblog** [comment]
I think that would be fine. It would be consistent with SELECT and RESET. They are console buttons and they are mappable to both controllers on the current version.

**Comment by sorgelig** [comment]
Unless P1/P2 difficulty is used exclusively for its player. Select and Reset has no assignment to specific player.

**Comment by skooterblog** [comment]
P1/P2 normal difficulty usage scenario is indeed associated with the correspondent player.

But I can think of three edge cases:

Moon Patrol and Pengo a two player games, P1 difficulty turns the music on or off regardless of which player the current turn is.
StarMaster is a single-player game, both P1 and P2 difficulty can be used (though it looks like they both have the same function).

**Comment by sorgelig** [comment]
ok. i see

**Comment by skooterblog** [comment]
Thank you for implementing this feature. I did some tests and they are working just fine.
