### ISSUE TITLE
Feature Request: Optional Stereo Sound

### ISSUE THREAD

**Issue by skooterblog** [MiSTer-devel/Atari2600_MiSTer#33]
Since the Atari 2600 is heading to its mature, maybe the developers can consider some bells and whistles like this.

The original Atari 2600 project would include stereo speakers and a few earlier games were projected to take advantage of them. Though they removed the speakers before the initial release, they kept the TIA with two separate audio outputs, so this is an easy mod in real hardware, and most emulators also support it. There are also some homebrews that take advantage of stereo sound.

I suggest this is optional, of course, because most games use the TIA channels randomly and sound weird in stereo.

**Comment by sorgelig** [comment]
would be good to get names of games using stereo output

**Comment by skooterblog** [comment]
I don't have a complete list, but some of the earlier games are:
- Combat
- Air Sea Battle
- Indy 500
- Street Racer
- Flag Capture
- Sky Diver
- Space War
- Outlaw
- Slot Racers
- Dragster

Homebrews:
- Medieval Mayhem
- Skeleton+

There are probably a few more.

**Comment by skooterblog** [comment]
Thank you for implementing this feature so fast. I've tested it in all these games and some others and it is working great.
The 50% and 75% options are also nice additions.
