### ISSUE TITLE
Can't initiate game in Activision games.

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/Atari2600_MiSTer#4]
Greetings,

I have run into this issue trying to run a few of my beloved Activision games: I can't seem to start any of them in the December build. I tried installing an earlier build but I encountered the same issue.
Atari games work fine, although they start with a press of the fire button, while I seem to remember Activision games required the player to press a button on the console itself to start them. None of the defined buttons seem to work in any case.
I apologize if I am missing something obvious — this has happened to me before!

I am running 128MB of RAM with direct video output.

Best regards.

**Comment by NML32** [comment]
Agreed, there seems to be a problem getting the Start & Select buttons on the controller to register in some games. 
There are a couple of things you can try.
1. have two controllers connected and see if Start & Select work on either controller.
2. Rapidly button mash the DPad, Start, and Select buttons. This sometimes gets them working.

**Comment by Left-Empty** [comment]
Thank you for your reply.
Indeed, setting up a second controller, the select and reset buttons of player 2 work!

Thank you for this very insightful workaround.

**Comment by bootsector** [comment]
It seems it was fixed in the latest release, as per quick tests done here. @Left-Empty do you confirm the same?

**Comment by Left-Empty** [comment]
Indeed, I configured the pad with the new buttons and it works perfectly!

I am quite new here: is it appropriate that I close it myself, or should I just let someone else do it?

**Comment by sorgelig** [comment]
the one who opened the issue is the first one who responsible for closing it if problem is solved.

**Comment by Left-Empty** [comment]
Thank you for the answer, closing it happily then!
