### ISSUE TITLE
Add support for additional mapper file extensions

### ISSUE THREAD

**Issue by tjanas** [MiSTer-devel/Atari2600_MiSTer#42]
The following four mappers with known game dumps require different mapper file extensions on Atari2600_MiSTer vs Analogue Nt Mini:
```
Analogue	BankswitchType  	MiSTer
.ACT	Activision 8K FE banking	.FE
.PB 	Parker Bros. E0 mapping 	.E0
.TV 	Tigervision 3F mapping  	.3F
.MN 	M-network E7 mapping    	.E7
```
Since Analogue is closed-source and Atari2600_MiSTer is open-source, would it be possible for Atari2600_MiSTer to be able to support these four additional file extensions and map them to their existing Atari2600_MiSTer equivalents?

**Comment by sorgelig** [comment]
I don't see why MiSTer should support Analogue extensions. Especially they aren't descriptive as MiSTer extensions.
