### ISSUE TITLE
Crystal Castles is not displaying dots

### ISSUE THREAD

**Issue by LamerDeluxe** [MiSTer-devel/Atari2600_MiSTer#5]
I've tried both the PAL and NTSC version and a different dump. All don't display any dots, which renders the game unplayable.

**Comment by NML32** [comment]
Crystal Castles is a Superchip game. Change the extension to .00s 
My Google sheet might help with other A2600 games. 
https://docs.google.com/spreadsheets/d/11XjIRX_cLhTF5Jau-hnYHHVP6LG1Af_G9J4_5fjr--I

**Comment by LamerDeluxe** [comment]
Thanks for the tip, just tried it with the SuperChip option and it works now.
