### ISSUE TITLE
Dig Dug boots to static screen. Unplayable

### ISSUE THREAD

**Issue by italiangrandma** [MiSTer-devel/Atari2600_MiSTer#50]
![2021-09-11 13_50_40-OBS 27 0 1 (64-bit, windows) - Profile_ ItalianGrandma - Scenes_ Untitled](https://user-images.githubusercontent.com/64335992/132956794-4d0d228f-4685-4155-9cce-90f55ed29c1b.png)

Dig Dug boots to this screen and you can't press anything to get past it. Rom is the version from HTGDB.

**Comment by sorgelig** [comment]
On this core some games have to be set to specific mapper through file extension.
dig dug should have extension .f6s

**Comment by italiangrandma** [comment]
Thanks @sorgelig, that fixed the issue!
