### ISSUE TITLE
Game Reset/Game Select nonfunctional in 19.09.27 build

### ISSUE THREAD

**Issue by thepulserifle** [MiSTer-devel/Atari2600_MiSTer#9]
Not currently possible to use Game Reset or Game Select in the Atari2600 core. Possibly due to firmware updates, as this was possible before?

**Comment by sorgelig** [comment]
Make sure you've updated to latest Main. Also define the buttons in 2600 again.

**Comment by thepulserifle** [comment]
I did that before submitting this bug report. Issue still persists.

**Comment by thepulserifle** [comment]
Issue vanished/fixed in latest build
